Repository limitusus/toggl-jobcan, pull requests merged in 2024-06, with the labels that each got.

#26 Use the latest toggl-worktime for Toggl API v9
  Gemfile.lock
  toggl-jobcan.gemspec
Labels: size/L

#27 Migrate CI from Travis to GHA
  .github/workflows/rspec.yml
  .travis.yml
  Gemfile.lock
  README.md
Labels: size/M

#28 upgrade Ruby and selenium-webdriver for toggl-jobcan version 0.5.0
  Dockerfile
Labels: size/XS
